#!/bin/bash

clear

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Menu
echo ""
echo -e "${RED}  (\_(\  ${NC}"
echo -e "${RED} (=’ :’) :* ${NC} Script by Mnm Ami"
echo -e "${RED}  (,(”)(”) °.¸¸.• ${NC}"
echo ""
echo -e "EDIT CONFIG OF CLOUD VPS ${RED}✿.｡.:* *.:｡✿*ﾟ’ﾟ･✿.｡.:*${NC}"
echo ""
echo -e "|${RED}1${NC}| OPENVPN CONFIG"
echo -e "|${RED}2${NC}| OPENVPN SERVER"
echo -e "|${RED}3${NC}| SQUID PROXY"
echo -e "|${RED}4${NC}| MENU"
echo -e "|${RED}5${NC}| "
echo -e "|${RED}6${NC}| "
echo ""
echo -e "|${RED}0${NC}| UPDATE EDIT CONFIG OF CLOUD VPS"
echo ""
echo -e "     ${RED}สามารถลัดเข้าฟังก์ชั่นนี้ด้วยการพิมคำว่า ed${NC}"
echo ""
read -p "Select a Choice : " EDIT

case $EDIT in

  1)
  
nano /etc/openvpn/client-common.txt
exit

  ;;

  2)
  
nano /etc/openvpn/server.conf
exit

  ;;

  3)

if [[ -e /etc/debian_version ]]; then
	OS=debian
	VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
  	if [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="17.04"' ]]; then
				nano /etc/squid/squid.conf
        exit
    elif [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
				nano /etc/squid3/squid.conf
        exit
    fi
fi

  ;;

  4)

nano /usr/local/bin/menu
exit

  ;;

  0)

rm -f /usr/local/bin/ed
wget -O /usr/local/bin/ed "https://raw.githubusercontent.com/nwqionm/OPENEXTRA/master/ed"
chmod +x /usr/local/bin/ed
ed

  ;;

esac
