#!/bin/bash

clear
GROUPNAME=nogroup
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
if [[ "$IP" = "" ]]; then
	IP=$(wget -4qO- "http://whatismyip.akamai.com/")
fi

# Color
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Menu
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
if [[ -e /usr/local/bin/Check-Thai ]]; then
	echo -e "เมนูสคริปท์ ${RED}✿.｡.:* *.:｡✿*ﾟ’ﾟ･✿.｡.:*${NC}"
	echo ""
	echo -e "|${RED} 1${NC}| เพิ่มบัญชีผู้ใช้"
	echo -e "|${RED} 2${NC}| ลบบัญชีผู้ใช้"
	echo -e "|${RED} 3${NC}| ตรวจสอบบัญชีผู้ใช้ทั้งหมด"
	echo -e "|${RED} 4${NC}| ตรวจสอบบัญชีที่กำลังเชื่อมต่อในขณะนี้"
	echo -e "|${RED} 5${NC}| เปลี่ยนวันหมดอายุของผู้ใช้"
	echo -e "|${RED} 6${NC}| ตั้งค่าเวลารีบูทเซิฟเวอร์อัตโนมัติ"
	echo -e "|${RED} 7${NC}| ทดสอบความเร็วอินเตอร์เน็ต"
	echo -e "|${RED} 8${NC}| ตรวจสอบแบนด์วิดท์"
	echo -e "|${RED} 9${NC}| ปรับเปลี่ยนระบบของเซิฟเวอร์"
	if [[ -e /usr/local/bin/Check-System ]]; then
		echo -e "|${RED}10${NC}| แบนและปลดแบนบัญชีผู้ใช้"
	elif [[ ! -e /usr/local/bin/Check-System ]]; then
		echo -e "|${RED}10${NC}| แบนและปลดแบนบัญชีผู้ใช้ ${RED}ใช้งานไม่ได้กับเซิฟเวอร์ระบบปัจจุบัน  ${NC}"
	fi
	echo -e "|${RED}11${NC}| ปรับความเร็วอินเตอร์เน็ต"
	echo -e "|${RED}12${NC}| เปิด-ปิด-รีสตาร์ท การทำงานของระบบ"
	echo -e "|${RED}13${NC}| แก้ไขคอนฟิกต่างๆในระบบ"
	echo ""
	echo -e "|${RED} 0${NC}| อัพเดตเมนูสคริปท์"
	echo -e "|${RED}00${NC}| เปลี่ยนเป็นภาษาอังกฤษ"

elif [[ ! -e /usr/local/bin/Check-Thai ]]; then
	echo -e "MENU SCRIPT ${RED}✿.｡.:* *.:｡✿*ﾟ’ﾟ･✿.｡.:*${NC}"
	echo ""
	echo -e "|${RED} 1${NC}| ADD NEW CLIENT"
	echo -e "|${RED} 2${NC}| REMOVE CLIENT"
	echo -e "|${RED} 3${NC}| CHECK ALL CLIENT"
	echo -e "|${RED} 4${NC}| CHECK ALL CLIENT ONLINE"
	echo -e "|${RED} 5${NC}| RENEW EXPIRE DATE OF CLIENT"
	echo -e "|${RED} 6${NC}| SET TIME AUTO REBOOT SERVER"
	echo -e "|${RED} 7${NC}| SPEEDTEST"
	echo -e "|${RED} 8${NC}| CHECK ALL BANDWIDTH"
	echo -e "|${RED} 9${NC}| CHANGE SYSTEM SERVER"
	if [[ -e /usr/local/bin/Check-System ]]; then
		echo -e "|${RED}10${NC}| BAN AND UNBAN CLIENT"
	elif [[ ! -e /usr/local/bin/Check-System ]]; then
		echo -e "|${RED}10${NC}| BAN AND UNBAN CLIENT ${RED}Not available with current server.  ${NC}"
	fi
	echo -e "|${RED}11${NC}| UP-DOWN SPEED INTERNET"
	echo -e "|${RED}12${NC}| START-STOP-RESTART OPERATION SYSTEM"
	echo -e "|${RED}13${NC}| EDIT CONFIG"
	echo ""
	echo -e "|${RED} 0${NC}| UPDATE MENU SCRIPT"
	echo -e "|${RED}00${NC}| เปลี่ยนเป็นภาษาไทย"
fi

echo ""
if [[ -e /etc/vnstat.conf ]]; then
	line=`cat /etc/openvpn/openvpn-status.log | wc -l`
	a=$((3+((line-8)/2)))
	b=$(((line-8)/2))
	cat /etc/openvpn/openvpn-status.log | head -n $a | tail -n $b | cut -d "," -f 1 | sed -e 's/,/   /g' > /usr/local/bin/Client-Login
	TOTAL=$(vnstat -i eth0 --nick local | grep "total:" | awk '{print $8" "substr ($9, 1, 1)}')
	TOTALONLINE=$(awk '{ total = total + NF }; END {print total}' /usr/local/bin/Client-Login)
	if [[ -e /usr/local/bin/Check-Thai ]]; then
		echo -e "แบนด์วิดท์ที่ใช้ไปทั้งหมด ${RED}$TOTAL${NC}${RED}B${NC}  |  ขณะนี้มีบัญชีที่กำลังเชื่อมต่อ ${RED}$TOTALONLINE${NC} บัญชี"
	elif [[ ! -e /usr/local/bin/Check-Thai ]]; then
		echo -e "TOTAL BANDWIDTH ${RED}$TOTAL${NC}${RED}B${NC}  |  CLIENT ONLINE NOW ${RED}$TOTALONLINE${NC} CLIENT"
	fi
fi
echo ""
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /usr/local/bin/Expire-List
	TOTALACCOUNTS=`cat /usr/local/bin/Expire-List | wc -l`
	for((i=1; i<=$TOTALACCOUNTS; i++ ))
		do
		TCLIENTVAL=`head -n $i /usr/local/bin/Expire-List | tail -n 1`
		CLIENT=`echo $TCLIENTVAL | cut -f1 -d:`
		CLIENTEXP=`echo $TCLIENTVAL | cut -f2 -d:`
		CLIENTEXPIREINSECONDS=$(( $CLIENTEXP * 86400 ))
		TODAYSTIME=`date +%s`

		if [ $CLIENTEXPIREINSECONDS -ge $TODAYSTIME ] ; then
			TIMETO1DAYS=$(( $TODAYSTIME + 86400 ))
				if [ $CLIENTEXPIREINSECONDS -le $TIMETO1DAYS ]; then
					if [[ -e /usr/local/bin/Check-Thai ]]; then
						echo -e "     ${RED}$CLIENT${NC} จะหมดอายุอีกไม่เกิน 24 ชั่วโมง"
					elif [[ ! -e /usr/local/bin/Check-Thai ]]; then
						echo -e "     ${RED}$CLIENT${NC} Will expire less more in 24 Hr."
					fi
				fi
		else
			$CLIENT=$(tail -n +2 /etc/openvpn/easy-rsa/pki/index.txt | grep "^V" | cut -d '=' -f 2)
			cd /etc/openvpn/easy-rsa/
			./easyrsa --batch revoke $CLIENT
			EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl
			rm -rf pki/reqs/$CLIENT.req
			rm -rf pki/private/$CLIENT.key
			rm -rf pki/issued/$CLIENT.crt
			rm -rf /etc/openvpn/crl.pem
			cp /etc/openvpn/easy-rsa/pki/crl.pem /etc/openvpn/crl.pem
			chown nobody:$GROUPNAME /etc/openvpn/crl.pem
			rm -f /home/vps/public_html/$CLIENT.ovpn
			userdel $CLIENT
			menu
			exit
		fi
	done
echo ""
if [[ -e /usr/local/bin/Check-Thai ]]; then
	read -p "เลือกหัวข้อเมนูที่ต้องการใช้งาน : " MENU
elif [[ ! -e /usr/local/bin/Check-Thai ]]; then
	read -p "Select a Menu Script : " MENU
fi

case $MENU in

	1) # ==================================================================================================================

CHECKSYSTEM=$(tail -n +2 /etc/openvpn/server.conf | grep "^username-as-common-name")
echo ""
read -p "ชื่อบัญชีที่ต้องการสร้าง : " -e CLIENT


if [[ -e /home/vps/public_html/$CLIENT.ovpn ]]; then
	echo ""
	echo "ชื่อบัญชีที่ระบุอยู่ในระบบแล้ว"
	echo ""
	read -p "กลับไปที่เมนู (Y or N) : " -e -i Y TOMENU

	if [[ "$TOMENU" = 'Y' ]]; then
		menu
		exit
	elif [[ "$TOMENU" = 'N' ]]; then
		exit
	fi
fi

if [[ $CHECKSYSTEM ]]; then
	read -p "รหัสผ่าน : " -e PASSWD
fi

echo ""
echo -e "     ${RED}ระบุตัวเลข 30 จะทำให้บัญชีที่สร้างใช้งานไม่ได้ในอีก 30 วัน${NC}"
read -p "กำหนดวันหมดอายุ : " -e TimeActive

clear
newclient () {
	cp /etc/openvpn/client-common.txt ~/$1.ovpn
	echo "<ca>" >> ~/$1.ovpn
	cat /etc/openvpn/easy-rsa/pki/ca.crt >> ~/$1.ovpn
	echo "</ca>" >> ~/$1.ovpn
	echo "<cert>" >> ~/$1.ovpn
	cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >> ~/$1.ovpn
	echo "</cert>" >> ~/$1.ovpn
	echo "<key>" >> ~/$1.ovpn
	cat /etc/openvpn/easy-rsa/pki/private/$1.key >> ~/$1.ovpn
	echo "</key>" >> ~/$1.ovpn
	echo "<tls-auth>" >> ~/$1.ovpn
	cat /etc/openvpn/ta.key >> ~/$1.ovpn
	echo "</tls-auth>" >> ~/$1.ovpn
}

cd /etc/openvpn/easy-rsa/
./easyrsa build-client-full $CLIENT nopass
newclient "$CLIENT"
cp /root/$CLIENT.ovpn /home/vps/public_html/
rm -f /root/$CLIENT.ovpn
useradd -e `date -d "$TimeActive days" +"%Y-%m-%d"` -s /bin/false -M $CLIENT
EXP="$(chage -l $CLIENT | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$PASSWD\n$PASSWD\n"|passwd $CLIENT &> /dev/null
clear
echo "ชื่อบัญชี : $CLIENT"
if [[ $CHECKSYSTEM ]]; then
	echo "รหัสผ่าน : $PASSWD"
fi
echo "หมดอายุในวันที่ : $EXP"
echo ""
echo "ดาวน์โหลดคอนฟิก : http://$IP:85/$CLIENT.ovpn"
echo ""
exit

	;;

	2) # ==================================================================================================================


NUMBEROFCLIENTS=$(tail -n +2 /etc/openvpn/easy-rsa/pki/index.txt | grep -c "^V")
if [[ "$NUMBEROFCLIENTS" = '0' ]]; then
	echo ""
	echo "ไม่เคยมีบัญชีอยู่ในระบบ"
	echo ""
	exit
fi

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
tail -n +2 /etc/openvpn/easy-rsa/pki/index.txt | grep "^V" | cut -d '=' -f 2 | nl -s '. '
if [[ "$NUMBEROFCLIENTS" = '1' ]]; then
	echo ""
	echo -e "${RED}คำเตือน${NC} : การออกจากหน้านี้ต้องกด CTRL+C เท่านั้น"
	echo "หากกด Enter จะทำการลบบัญชีลำดับที่ 1 โดยอัตโนมัติ"
	echo ""
	read -p "เลือกลำดับรายชื่อบัญชีที่ต้องการลบ [1] : " CLIENTNUMBER
else
	echo ""
	echo -e "${RED}คำเตือน${NC} : การออกจากหน้านี้ต้องกด CTRL+C เท่านั้น"
	echo "         หากกด Enter จะทำการลบบัญชีลำดับที่ 1 โดยอัตโนมัติ"
	echo ""
	read -p "เลือกลำดับรายชื่อบัญชีที่ต้องการลบ [1 - $NUMBEROFCLIENTS] : " CLIENTNUMBER
fi

CLIENT=$(tail -n +2 /etc/openvpn/easy-rsa/pki/index.txt | grep "^V" | cut -d '=' -f 2 | sed -n "$CLIENTNUMBER"p)
cd /etc/openvpn/easy-rsa/
./easyrsa --batch revoke $CLIENT
EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl
rm -rf pki/reqs/$CLIENT.req
rm -rf pki/private/$CLIENT.key
rm -rf pki/issued/$CLIENT.crt
rm -rf /etc/openvpn/crl.pem
cp /etc/openvpn/easy-rsa/pki/crl.pem /etc/openvpn/crl.pem
chown nobody:$GROUPNAME /etc/openvpn/crl.pem
rm -f /home/vps/public_html/$CLIENT.ovpn
userdel $CLIENT
echo ""
echo -e "ชื่อบัญชี ${RED}$CLIENT${NC} ถูกลบออกจากระบบเรียบร้อยแล้ว"
echo ""
exit

	;;

	3) # ==================================================================================================================

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
UIDN=1000
echo ""
echo -e "${RED}รายชื่อบัญชี          วันหมดอายุ ${NC} "
echo ""
while read CHECKCLIENT
do
	ACCOUNT="$(echo $CHECKCLIENT | cut -d: -f1)"
	ID="$(echo $CHECKCLIENT | grep -v nobody | cut -d: -f3)"
	EXP="$(chage -l $ACCOUNT | grep "Account expires" | awk -F": " '{print $2}')"
	if [[ $ID -ge $UIDN ]]; then
		printf "%-17s %2s\n" "$ACCOUNT" "$EXP"
	fi
done < /etc/passwd

TOTAL="$(awk -F: '$3 >= '$UIDN' && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo ""
echo -e "บัญชีทั้งหมด : ${RED}$TOTAL${NC} "
echo ""
exit

	;;

	4) # ==================================================================================================================

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
if [ -f "/etc/openvpn/openvpn-status.log" ]; then
	line=`cat /etc/openvpn/openvpn-status.log | wc -l`
	a=$((3+((line-8)/2)))
	b=$(((line-8)/2))

	echo -e "${RED}บัญชีที่กำลังเชื่อมต่ออยู่ในขณะนี้ ${NC} ";
	echo ""
	cat /etc/openvpn/openvpn-status.log | head -n $a | tail -n $b | cut -d "," -f 1 | sed -e 's/,/   /g' > /usr/local/bin/Client-Login
	cat /usr/local/bin/Client-Login
	echo ""
fi
TOTAL=$(awk '{ total = total + NF }; END {print total}' /usr/local/bin/Client-Login)
echo ""
echo -e "เชื่อมต่อทั้งหมด : ${RED}$TOTAL${NC} "
echo ""
exit

	;;


	5) # ==================================================================================================================

clear
echo ""
read -p "ชื่อบัญชีที่ต้องการเปลี่ยนวันหมดอายุ : " -e CLIENT

if [[ ! -e /home/vps/public_html/$CLIENT.ovpn ]]; then
	echo ""
	echo "ไม่มีชื่อบัญชีที่ระบุอยู่ในระบบ"
	echo ""
	read -p "กลับไปที่เมนู (Y or N) : " -e -i Y TOMENU

	if [[ "$TOMENU" = 'Y' ]]; then
		menu
		exit
	elif [[ "$TOMENU" = 'N' ]]; then
		exit
	fi
fi

EXP="$(chage -l $CLIENT | grep "Account expires" | awk -F": " '{print $2}')"
echo ""
echo -e "ชื่อบัญชีนี้หมดอายุในวันที่ ${RED}$EXP${NC}"
echo ""
read -p "เปลี่ยนวันหมดอายุ : " -e TimeActive

userdel $CLIENT
useradd -e `date -d "$TimeActive days" +"%Y-%m-%d"` -s /bin/false -M $CLIENT
EXP="$(chage -l $CLIENT | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$CLIENT\n$CLIENT\n"|passwd $CLIENT &> /dev/null
echo ""
echo "ชื่อบัญชี : $CLIENT"
echo "หมดวันหมดในวันที่ : $EXP"
echo ""
exit

	;;

	6) # ==================================================================================================================

 if [ ! -e /usr/local/bin/Reboot-Server ]; then
	echo '#!/bin/bash' > /usr/local/bin/Reboot-Server
	echo '' >> /usr/local/bin/Reboot-Server
	echo 'DATE=$(date +"%m-%d-%Y")' >> /usr/local/bin/Reboot-Server
	echo 'TIME=$(date +"%T")' >> /usr/local/bin/Reboot-Server
	echo 'echo "รีบูทเมื่อวันที่ $DATE เวลา $TIME" >> /usr/local/bin/Reboot-Log' >> /usr/local/bin/Reboot-Server
	echo '/sbin/shutdown -r now' >> /usr/local/bin/Reboot-Server
	chmod +x /usr/local/bin/Reboot-Server
fi

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
echo -e "${RED}ตั้งค่าเวลารีบูทเซิฟเวอร์อัตโนมัติ ${NC} "
echo ""
echo -e "|${RED}1${NC}| รีบูททุกๆ  1 ชั่วโมง"
echo -e "|${RED}2${NC}| รีบูททุกๆ  6 ชั่วโมง"
echo -e "|${RED}3${NC}| รีบูททุกๆ 12 ชั่วโมง"
echo -e "|${RED}4${NC}| รีบูททุกๆ  1 วัน"
echo -e "|${RED}5${NC}| รีบูททุกๆ  7 วัน"
echo -e "|${RED}6${NC}| รีบูททุกๆ 30 วัน"
echo -e "|${RED}7${NC}| หยุดการรีบูทเซิฟเวอร์"
echo -e "|${RED}8${NC}| ตรวจสอบดูบันทึกการรีบูทเซิฟเวอร์"
echo -e "|${RED}9${NC}| ลบบันทึกการรีบูทเซิฟเวอร์"
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " REBOOT

case $REBOOT in

	1)

echo "0 * * * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 1 ชั่วโมงเรียบร้อยแล้ว"
echo ""
exit

	;;

	2)

echo "0 */6 * * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 6 ชั่วโมงเรียบร้อยแล้ว"
echo ""
exit

	;;

	3)

echo "0 */12 * * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 12 ชั่วโมงเรียบร้อยแล้ว"
echo ""
exit

	;;

	4)

echo "0 0 * * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 1 วันเรียบร้อยแล้ว"
echo ""
exit

	;;

	5)

echo "0 0 */7 * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 7 วันเรียบร้อยแล้ว"
echo ""
exit

	;;

	6)

echo "0 0 1 * * root /usr/local/bin/Reboot-Server" > /etc/cron.d/Reboot-Server
echo ""
echo "ตั้งค่ารีบูทเซิฟเวอร์ทุกๆ 30 วันเรียบร้อยแล้ว"
echo ""
exit

	;;

	7)

rm -rf /usr/local/bin/Reboot-Server
echo ""
echo "หยุดการรีบูทเซิฟเวอร์เรียบร้อยแล้ว"
echo ""
exit

	;;

	8)

if [[ ! -e /usr/local/bin/Reboot-Log ]]; then
	echo ""
	echo "ไม่มีบันทึกการรีบูทเซิฟเวอร์"
	echo ""
	exit
else
	echo ""
	cat /usr/local/bin/Reboot-Log
	echo ""
	exit
fi

	;;

	9)

rm -rf /usr/local/bin/Reboot-Log
echo ""
echo "ลบบันทึกการรีบูทเซิฟเวอร์เรียบร้อยแล้ว"
echo ""
exit

	;;

esac

	;;

	7) # ==================================================================================================================

if [[ -e /usr/local/bin/speedtest ]]; then
	clear
	speedtest --share
elif [[ ! -e /usr/local/bin/speedtest ]]; then
	wget -O /usr/local/bin/speedtest "https://raw.githubusercontent.com/nwqionm/OPENEXTRA/master/speedtest"
	chmod +x /usr/local/bin/speedtest
	clear
	speedtest --share
fi

	;;

	8) # ==================================================================================================================

TODAY=$(vnstat -i eth0 | grep "today" | awk '{print $8" "substr ($9, 1, 1)}')
YESTERDAY=$(vnstat -i eth0 | grep "yesterday" | awk '{print $8" "substr ($9, 1, 1)}')
WEEK=$(vnstat -i eth0 -w | grep "current week" | awk '{print $9" "substr ($10, 1, 1)}')
RXWEEK=$(vnstat -i eth0 -w | grep "current week" | awk '{print $3" "substr ($10, 1, 1)}')
TXWEEK=$(vnstat -i eth0 -w | grep "current week" | awk '{print $6" "substr ($10, 1, 1)}')
MOUNT=$(vnstat -i eth0 | grep "`date +"%b '%y"`" | awk '{print $9" "substr ($10, 1, 1)}')
RXMOUNT=$(vnstat -i eth0 | grep "`date +"%b '%y"`" | awk '{print $3" "substr ($10, 1, 1)}')
TXMOUNT=$(vnstat -i eth0 | grep "`date +"%b '%y"`" | awk '{print $6" "substr ($10, 1, 1)}')
TOTAL=$(vnstat -i eth0 | grep "total:" | awk '{print $8" "substr ($9, 1, 1)}')
RXTOTAL=$(vnstat -i eth0 | grep "rx:" | awk '{print $2" "substr ($9, 1, 1)}')
TXTOTAL=$(vnstat -i eth0 | grep "tx:" | awk '{print $5" "substr ($9, 1, 1)}')

clear
echo ""
echo "  (\_(\ " | lolcat
echo " (=’ :’) :* Script by Mnm Ami" | lolcat
echo "  (,(”)(”) °.¸¸.•" | lolcat
echo ""
if [[ -e /usr/local/bin/Check-Thai ]]; then
	echo -e "แบนด์วิดท์ ${RED}✿.｡.:* *.:｡✿*ﾟ’ﾟ･✿.｡.:*${NC}"
	echo ""
	echo -e "วันนี้ ${RED}$TODAY${NC}"
	echo -e "เมื่อวานนี้ ${RED}$YESTERDAY${NC}"
	echo ""
	echo -e "รับข้อมูล (rx) ${RED}$RXWEEK${NC} ส่งข้อมูล (tx) ${RED}$TXWEEK${NC}"
	echo -e "สัปดาห์นี้ ${RED}$WEEK${NC}"
	echo ""
	echo -e "รับข้อมูล (rx) ${RED}$RXMOUNT${NC} ส่งข้อมูล (tx) ${RED}$TXMOUNT${NC}"
	echo -e "รวมทั้งหมดเฉพาะเดือนนี้ ${RED}$MOUNT${NC}"
	echo ""
	echo -e "รับข้อมูล (rx) ${RED}$RXTOTAL${NC} ส่งข้อมูล (tx) ${RED}$TXTOTAL${NC}"
	echo -e "รวมทั้งหมด ${RED}$TOTAL${NC}"
	echo ""
	exit

elif [[ ! -e /usr/local/bin/Check-Thai ]]; then
	echo -e "BANDWIDTH ${RED}✿.｡.:* *.:｡✿*ﾟ’ﾟ･✿.｡.:*${NC}"
	echo ""
	echo -e "TODAY ${RED}$TODAY${NC}"
	echo -e "YESTERDAY ${RED}$YESTERDAY${NC}"
	echo ""
	echo -e "RECEIVE (rx) ${RED}$RXWEEK${NC} TRANSMIT (tx) ${RED}$TXWEEK${NC}"
	echo -e "CURRENT WEEK ${RED}$WEEK${NC}"
	echo ""
	echo -e "RECEIVE (rx) ${RED}$RXMOUNT${NC} TRANSMIT (tx) ${RED}$TXMOUNT${NC}"
	echo -e "THIS MOUNT TOTAL ${RED}$MOUNT${NC}"
	echo ""
	echo -e "RECEIVE (rx) ${RED}$RXTOTAL${NC} TRANSMIT (tx) ${RED}$TXTOTAL${NC}"
	echo -e "TOTAL ${RED}$TOTAL${NC}"
	echo ""
	exit
fi

	;;

	9) # ==================================================================================================================

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
echo -e "${RED}ปรับเปลี่ยนระบบของเซิฟเวอร์ ${NC} "
echo ""
echo -e "|${RED}1${NC}| 1 ไฟล์เชื่อมต่อได้ 1 เครื่องเท่านั้น สามารถสร้างไฟล์เพิ่มได้"
echo -e "|${RED}2${NC}| 1 ไฟล์เชื่อมต่อได้หลายเครื่อง แต่ต้องสร้างบัญชีเพื่อใช้เชื่อมต่อ"
echo -e "|${RED}3${NC}| 1 ไฟล์เชื่อมต่อได้ไม่จำกัดเครื่อง"
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " CHANGESYSTEMSERVER

case $CHANGESYSTEMSERVER in

	1)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
echo "client-to-client" >> /etc/openvpn/server.conf
if [[ -e /usr/local/bin/Check-System ]]; then
	rm -rf /usr/local/bin/Check-System
fi
echo ""
echo "ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 1 เรียบร้อย"
echo ""
service openvpn restart

	;;

	2)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
echo "plugin /usr/lib/openvpn/openvpn-plugin-auth-pam.so /etc/pam.d/login
client-cert-not-required
username-as-common-name" >> /etc/openvpn/server.conf
echo "auth-user-pass" >> /etc/openvpn/client-common.txt
if [[ ! -e /usr/local/bin/Check-System ]]; then
	echo "Check System" >> /usr/local/bin/Check-System
fi
echo ""
echo "ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 2 เรียบร้อย"
echo ""
service openvpn restart

	;;

	3)

sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '28d' /etc/openvpn/server.conf
sed -i '20d' /etc/openvpn/client-common.txt
echo "duplicate-cn" >> /etc/openvpn/server.conf
if [[ -e /usr/local/bin/Check-System ]]; then
	rm -rf /usr/local/bin/Check-System
fi
echo ""
echo "ปรับเปลี่ยนระบบของเซิฟเวอร์เป็นรูปแบบที่ 3 เรียบร้อย"
echo ""
service openvpn restart

	;;

esac

	;;

	10) # ==================================================================================================================

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
echo -e "${RED}แบนและปลดแบนบัญชีผู้ใช้ ${NC} "
echo ""
echo -e "|${RED}1${NC}| แบนบัญชีผู้ใช้"
echo -e "|${RED}2${NC}| ปลดแบนบัญชีผู้ใช้"
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " BandUB

case $BandUB in

	1)

echo ""
read -p "ชื่อบัญชีที่ต้องการแบน : " CLIENT

egrep "^$CLIENT" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
	echo "V=$CLIENT" >> /usr/local/bin/Ban-Unban
	passwd -l $CLIENT
	clear
	echo ""
	echo "บัญชีชื่อ $CLIENT ได้ถูกแบนเรียบร้อยแล้ว"
	echo ""
	exit
elif [ $? -eq 1 ]; then
	clear
	echo ""
	echo "ไม่มีชื่อบัญชีที่ระบุอยู่ในระบบ"
	echo ""
	read -p "กลับไปที่เมนู (Y or N) : " -e -i Y TOMENU

	if [[ "$TOMENU" = 'Y' ]]; then
		menu
		exit
	elif [[ "$TOMENU" = 'N' ]]; then
		exit
	fi
fi

	;;

	2)

echo ""
read -p "ชื่อบัญชีที่ต้องการปลดแบน : " CLIENT

egrep "^$CLIENT" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
	sed -i 's/V=$CLIENT/R=$CLIENT/g' /usr/local/bin/Ban-Unban
	passwd -u $CLIENT
	clear
	echo ""
	echo "บัญชีชื่อ $CLIENT ได้ถูกปลดแบนเรียบร้อยแล้ว"
	echo ""
	
	exit

elif [ $? -eq 1 ]; then
	clear
	echo ""
	echo "ชื่อบัญชีที่ระบุไม่ได้ถูกแบน หรือไม่มีชื่อบัญชีที่ระบุอยู่ในระบบ"
	echo ""
	read -p "กลับไปที่เมนู (Y or N) : " -e -i Y TOMENU

	if [[ "$TOMENU" = 'Y' ]]; then
		menu
		exit
	elif [[ "$TOMENU" = 'N' ]]; then
		exit
	fi
fi

	;;

esac

	;;

	11) # ==================================================================================================================

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
if [[ ! -e /etc/trickled.conf ]]; then
	apt-get install trickle
	echo -e "${RED}โปรดอ่าน${NC} : หน่วยวัดขนาดความเร็วต้องระบุเป็น Kilobyte (Kb)"
	echo "          วิธีการคำนวนเพื่อให้ได้หน่วยวัด Kilobyte ( 1024 x Mb = Kb )"
	echo "          นำเลข 1024 คูณด้วยจำนวน Mb ที่ต้องการ ผลลัพธ์ที่ออกจะได้เป็น Kb"
	echo -e "             5 Mb =    ${RED}5120${NC} Kb"
	echo -e "            10 Mb =   ${RED}10240${NC} Kb"
	echo -e "            20 Mb =   ${RED}20480${NC} Kb"
	echo -e "            50 Mb =   ${RED}51200${NC} Kb"
	echo -e "           100 Mb =  ${RED}102400${NC} Kb"
	echo -e "           500 Mb =  ${RED}512000${NC} Kb"
	echo -e "          1000 Mb = ${RED}1024000${NC} Kb"
	echo -e "          2000 Mb = ${RED}2048000${NC} Kb"
	echo ""
	echo -e "หากต้องการยกเลิกให้กด CTRL+C"
	echo ""
	read -p "ปรับความเร็วอินเตอร์เน็ต (ดาวน์โหลด) : " -e DOWNLOAD
	read -p "ปรับความเร็วอินเตอร์เน็ต (อัพโหลด) : " -e UPLOAD

	echo ""
	echo -e "Success : Download ${RED}$DOWNLOAD${NC} Kbps | Upload ${RED}$UPLOAD${NC} Kbps"
	echo ""
	trickle -d $DOWNLOAD -u $UPLOAD bash
	exit

elif [[ -e /etc/trickled.conf ]]; then
	echo -e "${RED}โปรดอ่าน${NC} : หน่วยวัดขนาดความเร็วต้องระบุเป็น Kilobyte (Kb)"
	echo "          วิธีการคำนวนเพื่อให้ได้หน่วยวัด Kilobyte ( 1024 x Mb = Kb )"
	echo "          นำเลข 1024 คูณด้วยจำนวน Mb ที่ต้องการ ผลลัพธ์ที่ออกจะได้เป็น Kb"
	echo -e "             5 Mb =    ${RED}5120${NC} Kb"
	echo -e "            10 Mb =   ${RED}10240${NC} Kb"
	echo -e "            20 Mb =   ${RED}20480${NC} Kb"
	echo -e "            50 Mb =   ${RED}51200${NC} Kb"
	echo -e "           100 Mb =  ${RED}102400${NC} Kb"
	echo -e "           500 Mb =  ${RED}512000${NC} Kb"
	echo -e "          1000 Mb = ${RED}1024000${NC} Kb"
	echo -e "          2000 Mb = ${RED}2048000${NC} Kb"
	echo ""
	echo -e "หากต้องการยกเลิกให้กด CTRL+C"
	echo ""
	read -p "ปรับความเร็วอินเตอร์เน็ต (ดาวน์โหลด) : " -e DOWNLOAD
	read -p "ปรับความเร็วอินเตอร์เน็ต (อัพโหลด) : " -e UPLOAD

	echo ""
	echo -e "Success : Download ${RED}$DOWNLOAD${NC} Kbps | Upload ${RED}$UPLOAD${NC} Kbps"
	echo ""
	trickle -d $DOWNLOAD -u $UPLOAD bash
	exit
fi

	;;

	12) # ==================================================================================================================

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
echo -e "เปิด-ปิด-รีสตาร์ท การทำงานของระบบ ${RED}✿.｡.:* *.:｡✿*ﾟ’ﾟ･✿.｡.:*${NC}"
echo ""
echo -e "|${RED}1${NC}| OPENVPN"
echo -e "|${RED}2${NC}| SSH DROPBEAR"
echo -e "|${RED}3${NC}| SQUID PROXY"
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " SERVICE

case $SERVICE in

	1)

	echo ""
	echo -e "	|${RED}1${NC}| เปิด"
	echo -e "	|${RED}2${NC}| ปิด"
	echo -e "	|${RED}3${NC}| รีสตาร์ท"
	echo ""
	read -p "	เลือกหัวข้อที่ต้องการใช้งาน : " SERVICEOPENVPN

	case $SERVICEOPENVPN in

		1)
	service openvpn start
	echo ""
	echo -e "	OpenVPN ${RED}STARTED${NC}"
	echo ""
	exit
		;;

		2)
	service openvpn stop
	echo ""
	echo -e "	OpenVPN ${RED}STOPPED${NC}"
	echo ""
	exit
		;;

		3)
	service openvpn restart
	echo ""
	echo -e "	OpenVPN ${RED}RESTARTED${NC}"
	echo ""
	exit
		;;

	esac

	;;

	2)

	echo ""
	echo -e "	|${RED}1${NC}| เปิด"
	echo -e "	|${RED}2${NC}| ปิด"
	echo -e "	|${RED}3${NC}| รีสตาร์ท"
	echo ""
	read -p "	เลือกหัวข้อที่ต้องการใช้งาน : " SERVICEDROPBEAR

	case $SERVICEDROPBEAR in

		1)

	if [[ -e /etc/default/dropbear ]]; then
		service ssh start
		echo ""
		echo -e "	SSH Dropbear ${RED}STARTED${NC}"
		echo ""
		exit
	elif [[ ! -e /etc/default/dropbear ]]; then
		echo ""
		echo "	ยังไม่ได้ติดตั้ง SSH Dropbear"
		echo ""
		exit
	fi
		;;

		2)
	if [[ -e /etc/default/dropbear ]]; then
		service ssh stop
		echo ""
		echo -e "	SSH Dropbear ${RED}STOPPED${NC}"
		echo ""
		exit
	elif [[ ! -e /etc/default/dropbear ]]; then
		echo ""
		echo "	ยังไม่ได้ติดตั้ง SSH Dropbear"
		echo ""
		exit
	fi
		;;

		3)
	if [[ -e /etc/default/dropbear ]]; then
		service ssh restart
		echo ""
		echo -e "	SSH Dropbear ${RED}RESTARTED${NC}"
		echo ""
		exit
	elif [[ ! -e /etc/default/dropbear ]]; then
		echo ""
		echo "	ยังไม่ได้ติดตั้ง SSH Dropbear"
		echo ""
		exit
	fi
		;;

	esac

	;;

	3)

	echo ""
	echo -e "	|${RED}1${NC}| เปิด"
	echo -e "	|${RED}2${NC}| ปิด"
	echo -e "	|${RED}3${NC}| รีสตาร์ท"
	echo ""
	read -p "	เลือกหัวข้อที่ต้องการใช้งาน : " SERVICEPROXY

	case $SERVICEPROXY in

		1)
	if [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="17.04"' ]]; then
		if [[ ! -e /etc/squid/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid start
			echo ""
			echo -e "	Squid Proxy ${RED}STARTED${NC}"
			echo ""
			exit
		fi
	elif [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		if [[ ! -e /etc/squid3/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid3 start
			echo ""
			echo -e "	Squid Proxy ${RED}STARTED${NC}"
			echo ""
			exit
		fi
	fi
		;;

		2)
	if [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="17.04"' ]]; then
		if [[ ! -e /etc/squid/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid stop
			echo ""
			echo -e "	Squid Proxy ${RED}STOPPED${NC}"
			echo ""
			exit
		fi
	elif [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		if [[ ! -e /etc/squid3/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid3 stop
			echo ""
			echo -e "	Squid Proxy ${RED}STOPPED${NC}"
			echo ""
			exit
		fi
	fi
		;;

		3)
	if [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="17.04"' ]]; then
		if [[ ! -e /etc/squid/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid restart
			echo ""
			echo -e "	Squid Proxy ${RED}RESTARTED${NC}"
			echo ""
			exit
		fi
	elif [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
		if [[ ! -e /etc/squid3/squid.conf ]]; then
			echo ""
			echo "	ยังไม่ได้ติดตั้ง Squid Proxy"
			echo ""
			exit
		else
			service squid3 restart
			echo ""
			echo -e "	Squid Proxy ${RED}RESTARTED${NC}"
			echo ""
			exit
		fi
	fi
		;;

	esac

	;;

esac

	;;

	13) # ==================================================================================================================

clear
echo ""
echo "  (\_(\ "
echo " (=’ :’) :* Script by Mnm Ami"
echo "  (,(”)(”) °.¸¸.•"
echo ""
echo -e "แก้ไขคอนฟิกต่างๆในระบบ ${RED}✿.｡.:* *.:｡✿*ﾟ’ﾟ･✿.｡.:*${NC}"
echo ""
echo -e "|${RED}1${NC}| OPENVPN ไฟล์ต้นแบบการสร้างคอนฟิก"
echo -e "|${RED}2${NC}| OPENVPN ไฟล์ข้อมูลเซิฟเวอร์"
echo -e "|${RED}3${NC}| SQUID PROXY ไฟล์รายละเอียดของพร็อกซี่"
echo -e "|${RED}4${NC}| MENU ไฟล์สคริปท์ของเมนู"
echo -e "|${RED}5${NC}| "
echo -e "|${RED}6${NC}| "
echo ""
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " EDIT

case $EDIT in

	1)
nano /etc/openvpn/client-common.txt
exit
	;;
	2)
nano /etc/openvpn/server.conf
exit
	;;
	3)
if [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="17.04"' ]]; then
	nano /etc/squid/squid.conf
	exit
elif [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
	nano /etc/squid3/squid.conf
	exit
fi
	;;
	4)
nano /usr/local/bin/menu
exit
	;;

esac

	;;

	0) # ==================================================================================================================

rm -f /usr/local/bin/menu
wget -O /usr/local/bin/menu "https://raw.githubusercontent.com/nwqionm/OPENEXTRA/master/menu"
chmod +x /usr/local/bin/menu
menu

	;;

	00) # ==================================================================================================================

if [[ -e /usr/local/bin/Check-Thai ]]; then
	rm -f /usr/local/bin/Check-Thai
	menu
elif [[ ! -e /usr/local/bin/Check-Thai ]]; then
	echo "Check Thai" >> /usr/local/bin/Check-Thai
	menu
fi

	;;
	
	000)

	echo "#!/usr/bin/env python

__version__ = '0.1.1'

source = None
shutdown_event = None

import os
import re
import sys
import math
import signal
import socket
import timeit
import threading

socket_socket = socket.socket

try:
import xml.etree.cElementTree as ET
except ImportError:
try:
import xml.etree.ElementTree as ET
except ImportError:
from xml.dom import minidom as DOM
ET = None

try:
from urllib2 import urlopen, Request, HTTPError, URLError
except ImportError:
from urllib.request import urlopen, Request, HTTPError, URLError

try:
from httplib import HTTPConnection, HTTPSConnection
except ImportError:
from http.client import HTTPConnection, HTTPSConnection

try:
from Queue import Queue
except ImportError:
from queue import Queue

try:
from urlparse import urlparse
except ImportError:
from urllib.parse import urlparse

try:
from urlparse import parse_qs
except ImportError:
try:
from urllib.parse import parse_qs
except ImportError:
from cgi import parse_qs

try:
from hashlib import md5
except ImportError:
from md5 import md5

try:
from argparse import ArgumentParser as ArgParser
except ImportError:
from optparse import OptionParser as ArgParser

try:
import builtins
except ImportError:
def print_(*args, **kwargs):
"""The new-style print function taken from
https://pypi.python.org/pypi/six/

"""
fp = kwargs.pop("file", sys.stdout)
if fp is None:
return

def write(data):
if not isinstance(data, basestring):
data = str(data)
fp.write(data)

want_unicode = False
sep = kwargs.pop("sep", None)
if sep is not None:
if isinstance(sep, unicode):
want_unicode = True
elif not isinstance(sep, str):
raise TypeError("sep must be None or a string")
end = kwargs.pop("end", None)
if end is not None:
if isinstance(end, unicode):
want_unicode = True
elif not isinstance(end, str):
raise TypeError("end must be None or a string")
if kwargs:
raise TypeError("invalid keyword arguments to print()")
if not want_unicode:
for arg in args:
if isinstance(arg, unicode):
want_unicode = True
break
if want_unicode:
newline = unicode("\n")
space = unicode(" ")
else:
newline = "\n"
space = " "
if sep is None:
sep = space
if end is None:
end = newline
for i, arg in enumerate(args):
if i:
write(sep)
write(arg)
write(end)
else:
print_ = getattr(builtins, 'print')
del builtins


def bound_socket(*args, **kwargs):
"""Bind socket to a specified source IP address"""

global source
sock = socket_socket(*args, **kwargs)
sock.bind((source, 0))
return sock


def distance(origin, destination):
"""Determine distance between 2 sets of [lat,lon] in km"""

lat1, lon1 = origin
lat2, lon2 = destination
radius = 6371  # km

dlat = math.radians(lat2 - lat1)
dlon = math.radians(lon2 - lon1)
a = (math.sin(dlat / 2) * math.sin(dlat / 2) + math.cos(math.radians(lat1))
* math.cos(math.radians(lat2)) * math.sin(dlon / 2)
* math.sin(dlon / 2))
c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
d = radius * c

return d


class FileGetter(threading.Thread):
"""Thread class for retrieving a URL"""

def __init__(self, url, start):
self.url = url
self.result = None
self.starttime = start
threading.Thread.__init__(self)

def run(self):
self.result = [0]
try:
if (timeit.default_timer() - self.starttime) <= 10:
f = urlopen(self.url)
while 1 and not shutdown_event.isSet():
self.result.append(len(f.read(10240)))
if self.result[-1] == 0:
break
f.close()
except IOError:
pass


def downloadSpeed(files, quiet=False):
"""Function to launch FileGetter threads and calculate download speeds"""

start = timeit.default_timer()

def producer(q, files):
for file in files:
thread = FileGetter(file, start)
thread.start()
q.put(thread, True)
if not quiet and not shutdown_event.isSet():
sys.stdout.write('.')
sys.stdout.flush()

finished = []

def consumer(q, total_files):
while len(finished) < total_files:
thread = q.get(True)
while thread.isAlive():
thread.join(timeout=0.1)
finished.append(sum(thread.result))
del thread

q = Queue(6)
prod_thread = threading.Thread(target=producer, args=(q, files))
cons_thread = threading.Thread(target=consumer, args=(q, len(files)))
start = timeit.default_timer()
prod_thread.start()
cons_thread.start()
while prod_thread.isAlive():
prod_thread.join(timeout=0.1)
while cons_thread.isAlive():
cons_thread.join(timeout=0.1)
return (sum(finished) / (timeit.default_timer() - start))


class FilePutter(threading.Thread):
"""Thread class for putting a URL"""

def __init__(self, url, start, size):
self.url = url
chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
data = chars * (int(round(int(size) / 36.0)))
self.data = ('content1=%s' % data[0:int(size) - 9]).encode()
del data
self.result = None
self.starttime = start
threading.Thread.__init__(self)

def run(self):
try:
if ((timeit.default_timer() - self.starttime) <= 10 and
not shutdown_event.isSet()):
f = urlopen(self.url, self.data)
f.read(11)
f.close()
self.result = len(self.data)
else:
self.result = 0
except IOError:
self.result = 0


def uploadSpeed(url, sizes, quiet=False):
"""Function to launch FilePutter threads and calculate upload speeds"""

start = timeit.default_timer()

def producer(q, sizes):
for size in sizes:
thread = FilePutter(url, start, size)
thread.start()
q.put(thread, True)
if not quiet and not shutdown_event.isSet():
sys.stdout.write('.')
sys.stdout.flush()

finished = []

def consumer(q, total_sizes):
while len(finished) < total_sizes:
thread = q.get(True)
while thread.isAlive():
thread.join(timeout=0.1)
finished.append(thread.result)
del thread

q = Queue(6)
prod_thread = threading.Thread(target=producer, args=(q, sizes))
cons_thread = threading.Thread(target=consumer, args=(q, len(sizes)))
start = timeit.default_timer()
prod_thread.start()
cons_thread.start()
while prod_thread.isAlive():
prod_thread.join(timeout=0.1)
while cons_thread.isAlive():
cons_thread.join(timeout=0.1)
return (sum(finished) / (timeit.default_timer() - start))


def getAttributesByTagName(dom, tagName):
"""Retrieve an attribute from an XML document and return it in a
consistent format

Only used with xml.dom.minidom, which is likely only to be used
with python versions older than 2.5
"""
elem = dom.getElementsByTagName(tagName)[0]
return dict(list(elem.attributes.items()))


def getConfig():
"""Download the speedtest.net configuration and return only the data
we are interested in
"""

uh = urlopen('http://www.speedtest.net/speedtest-config.php')
configxml = []
while 1:
configxml.append(uh.read(10240))
if len(configxml[-1]) == 0:
break
if int(uh.code) != 200:
return None
uh.close()
try:
try:
root = ET.fromstring(''.encode().join(configxml))
config = {
'client': root.find('client').attrib,
'times': root.find('times').attrib,
'download': root.find('download').attrib,
'upload': root.find('upload').attrib}
except AttributeError:
root = DOM.parseString(''.join(configxml))
config = {
'client': getAttributesByTagName(root, 'client'),
'times': getAttributesByTagName(root, 'times'),
'download': getAttributesByTagName(root, 'download'),
'upload': getAttributesByTagName(root, 'upload')}
except SyntaxError:
print_('Failed to parse speedtest.net configuration')
sys.exit(1)
del root
del configxml
return config


def closestServers(client, all=False):
"""Determine the 5 closest speedtest.net servers based on geographic
distance
"""

uh = urlopen('http://www.speedtest.net/speedtest-servers-static.php')
serversxml = []
while 1:
serversxml.append(uh.read(10240))
if len(serversxml[-1]) == 0:
break
if int(uh.code) != 200:
return None
uh.close()
try:
try:
root = ET.fromstring(''.encode().join(serversxml))
elements = root.getiterator('server')
except AttributeError:
root = DOM.parseString(''.join(serversxml))
elements = root.getElementsByTagName('server')
except SyntaxError:
print_('Failed to parse list of speedtest.net servers')
sys.exit(1)
servers = {}
for server in elements:
try:
attrib = server.attrib
except AttributeError:
attrib = dict(list(server.attributes.items()))
d = distance([float(client['lat']), float(client['lon'])],
[float(attrib.get('lat')), float(attrib.get('lon'))])
attrib['d'] = d
if d not in servers:
servers[d] = [attrib]
else:
servers[d].append(attrib)
del root
del serversxml
del elements

closest = []
for d in sorted(servers.keys()):
for s in servers[d]:
closest.append(s)
if len(closest) == 5 and not all:
break
else:
continue
break

del servers
return closest


def getBestServer(servers):
"""Perform a speedtest.net latency request to determine which
speedtest.net server has the lowest latency
"""

results = {}
for server in servers:
cum = []
url = '%s/latency.txt' % os.path.dirname(server['url'])
urlparts = urlparse(url)
for i in range(0, 3):
try:
if urlparts[0] == 'https':
h = HTTPSConnection(urlparts[1])
else:
h = HTTPConnection(urlparts[1])
start = timeit.default_timer()
h.request("GET", urlparts[2])
r = h.getresponse()
total = (timeit.default_timer() - start)
except (HTTPError, URLError, socket.error):
cum.append(3600)
continue
text = r.read(9)
if int(r.status) == 200 and text == 'test=test'.encode():
cum.append(total)
else:
cum.append(3600)
h.close()
avg = round((sum(cum) / 6) * 1000, 3)
results[avg] = server
fastest = sorted(results.keys())[0]
best = results[fastest]
best['latency'] = fastest

return best


def ctrl_c(signum, frame):
"""Catch Ctrl-C key sequence and set a shutdown_event for our threaded
operations
"""

global shutdown_event
shutdown_event.set()
raise SystemExit('\nCancelling...')


def version():
"""Print the version"""

raise SystemExit(__version__)


def speedtest():
"""Run the full speedtest.net test"""

global shutdown_event, source
shutdown_event = threading.Event()

signal.signal(signal.SIGINT, ctrl_c)

description = (
'Command line interface for testing internet bandwidth using '
'speedtest.net.\n'
'------------------------------------------------------------'
'--------------\n'
'https://github.com/sivel/speedtest-cli')

parser = ArgParser(description=description)

try:
parser.add_argument = parser.add_option
except AttributeError:
pass
parser.add_argument('--bytes', dest='units', action='store_const',
const=('bytes', 1), default=('bits', 8),
help='Display values in bytes instead of bits. Does '
'not affect the image generated by --share')
parser.add_argument('--share', action='store_true',
help='Generate and provide a URL to the speedtest.net '
'share results image')
parser.add_argument('--simple', action='store_true',
help='Suppress verbose output, only show basic '
'information')
parser.add_argument('--list', action='store_true',
help='Display a list of speedtest.net servers '
'sorted by distance')
parser.add_argument('--server', help='Specify a server ID to test against')
parser.add_argument('--mini', help='URL of the Speedtest Mini server')
parser.add_argument('--source', help='Source IP address to bind to')
parser.add_argument('--version', action='store_true',
help='Show the version number and exit')

options = parser.parse_args()
if isinstance(options, tuple):
args = options[0]
else:
args = options
del options

if args.version:
version()

if args.source:
source = args.source
socket.socket = bound_socket

if not args.simple:
print_('Retrieving speedtest.net configuration...')
try:
config = getConfig()
except URLError:
print_('Cannot retrieve speedtest configuration')
sys.exit(1)

if not args.simple:
print_('Retrieving speedtest.net server list...')
if args.list or args.server:
servers = closestServers(config['client'], True)
if args.list:
serverList = []
for server in servers:
line = ('%(id)4s) %(sponsor)s (%(name)s, %(country)s) '
'[%(d)0.2f km]' % server)
serverList.append(line)

try:
unicode()
print_('\n'.join(serverList).encode('utf-8', 'ignore'))
except NameError:
print_('\n'.join(serverList))
except IOError:
pass
sys.exit(0)
else:
servers = closestServers(config['client'])

if not args.simple:
print_('Testing from %(isp)s (%(ip)s)...' % config['client'])

if args.server:
try:
best = getBestServer(filter(lambda x: x['id'] == args.server,
servers))
except IndexError:
print_('Invalid server ID')
sys.exit(1)
elif args.mini:
name, ext = os.path.splitext(args.mini)
if ext:
url = os.path.dirname(args.mini)
else:
url = args.mini
urlparts = urlparse(url)
try:
f = urlopen(args.mini)
except:
print_('Invalid Speedtest Mini URL')
sys.exit(1)
else:
text = f.read()
f.close()
extension = re.findall('upload_extension: "([^"]+)"', text.decode())
if not extension:
for ext in ['php', 'asp', 'aspx', 'jsp']:
try:
f = urlopen('%s/speedtest/upload.%s' % (args.mini, ext))
except:
pass
else:
data = f.read().strip()
if (f.code == 200 and
len(data.splitlines()) == 1 and
re.match('size=[0-9]', data)):
extension = [ext]
break
if not urlparts or not extension:
print_('Please provide the full URL of your Speedtest Mini server')
sys.exit(1)
servers = [{
'sponsor': 'Speedtest Mini',
'name': urlparts[1],
'd': 0,
'url': '%s/speedtest/upload.%s' % (url.rstrip('/'), extension[0]),
'latency': 0,
'id': 0
}]
try:
best = getBestServer(servers)
except:
best = servers[0]
else:
if not args.simple:
print_('Selecting best server based on latency...')
best = getBestServer(servers)

if not args.simple:

try:
unicode()
print_(('Hosted by %(sponsor)s (%(name)s) [%(d)0.2f km]: '
'%(latency)s ms' % best).encode('utf-8', 'ignore'))
except NameError:
print_('Hosted by %(sponsor)s (%(name)s) [%(d)0.2f km]: '
'%(latency)s ms' % best)
else:
print_('Ping: %(latency)s ms' % best)

sizes = [350, 500, 750, 1000, 1500, 2000, 2500, 3000, 3500, 4000]
urls = []
for size in sizes:
for i in range(0, 4):
urls.append('%s/random%sx%s.jpg' %
(os.path.dirname(best['url']), size, size))
if not args.simple:
print_('Testing download speed', end='')
dlspeed = downloadSpeed(urls, args.simple)
if not args.simple:
print_()
print_('Download: %0.2f M%s/s' %
((dlspeed / 1000 / 1000) * args.units[1], args.units[0]))

sizesizes = [int(.25 * 1000 * 1000), int(.5 * 1000 * 1000)]
sizes = []
for size in sizesizes:
for i in range(0, 25):
sizes.append(size)
if not args.simple:
print_('Testing upload speed', end='')
ulspeed = uploadSpeed(best['url'], sizes, args.simple)
if not args.simple:
print_()
print_('Upload: %0.2f M%s/s' %
((ulspeed / 1000 / 1000) * args.units[1], args.units[0]))

if args.share and args.mini:
print_('Cannot generate a speedtest.net share results image while '
'testing against a Speedtest Mini server')
elif args.share:
dlspeedk = int(round((dlspeed / 1000) * 8, 0))
ping = int(round(best['latency'], 0))
ulspeedk = int(round((ulspeed / 1000) * 8, 0))

apiData = [
'download=%s' % dlspeedk,
'ping=%s' % ping,
'upload=%s' % ulspeedk,
'promo=',
'startmode=%s' % 'pingselect',
'recommendedserverid=%s' % best['id'],
'accuracy=%s' % 1,
'serverid=%s' % best['id'],
'hash=%s' % md5(('%s-%s-%s-%s' %
(ping, ulspeedk, dlspeedk, '297aae72'))
.encode()).hexdigest()]

req = Request('http://www.speedtest.net/api/api.php',
data='&'.join(apiData).encode())
req.add_header('Referer', 'http://c.speedtest.net/flash/speedtest.swf')
f = urlopen(req)
response = f.read()
code = f.code
f.close()

if int(code) != 200:
print_('Could not submit results to speedtest.net')
sys.exit(1)

qsargs = parse_qs(response.decode())
resultid = qsargs.get('resultid')
if not resultid or len(resultid) != 1:
print_('Could not submit results to speedtest.net')
sys.exit(1)

print_('Share results: http://www.speedtest.net/result/%s.png' %
resultid[0])


def main():
try:
speedtest()
except KeyboardInterrupt:
print_('\nCancelling...')


if __name__ == '__main__':
main()

# vim:ts=4:sw=4:expandtab" >> /usr/local/bin/speedtest

	;;

esac
